/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JavaSwingUI;

import JavaSwingModels.User;
import javax.swing.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;


/**
 *
 * @author eboka
 */
public class ViewPage extends javax.swing.JPanel {

    /**
     * Creates new form ViewPage
     */
    User user;
    private JLabel imageLabel;
    
    public ViewPage(User user) {
        initComponents();
        this.user = user;    

// Researched with Stackvoerflow and Chatgpt to be able to view image in TextPane
     
        imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(SwingConstants.CENTER);
        imageLabel.setVerticalAlignment(SwingConstants.CENTER);
        imageLabel.setPreferredSize(new Dimension(200, 200));

        // Add the image label to the layout
        add(imageLabel, BorderLayout.SOUTH); // Adjust the position as necessary

        if(this.user != null){
        String message = "First Name: " +user.getFirstName()+ ", Last Name: " +user.getLastName()+ ", Age: " +user.getAge()+ "\n" 
                + "\n" +
                "Gender: " +user.getGender()+ "\n" 
                + "\n" +
                "Date of Birth: " +user.getDateChooser()+ "\n"
                 + "\n" +
                "Patient Type: " +user.getPatientType()+ "\n"
                + "\n" +
                "Email: " +user.getEmail()+ "\n" 
                + "\n" +
                "Additional Message: " +user.getScTextArea()+ "\n" 
                + "\n";
      
      
         txtDetails.setText(message); 
         
         updateImage(user.getPic());
         
//         ImageIcon imagePath = user.getPic(); // Assuming user.getPic() returns the image path
//            updateImage(imagePath);
        
        }else{
            
         String message = "Details Not Provided... Please Try Again";
         txtDetails.setText(message);   
            
              JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    
    private void updateImage(ImageIcon imageIcon) {
    if (imageIcon != null) {
        // Scale the image to fit the label dimensions
        Image scaledImage = imageIcon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(scaledImage));
    } else {
        imageLabel.setIcon(null); // Clear the image if none is provided
    }
}
    
//private void updateImage(ImageIcon imagePath) {
//    if (imagePath != null) {
//        // Set the icon to the label
//        imageLabel.setIcon(imagePath);
//    } else {
//        JOptionPane.showMessageDialog(this, "Image not found!", "Error", JOptionPane.ERROR_MESSAGE);
//    }
//}
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewPage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextPane();

        lblViewPage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblViewPage.setText("Patient Details View");

        jScrollPane2.setViewportView(txtDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblViewPage, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblViewPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblViewPage;
    private javax.swing.JTextPane txtDetails;
    // End of variables declaration//GEN-END:variables
}
