/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JPanel;
import models.TaskManagementModel;

/**
 *
 * @author eboka
 */
public class AdminPageView extends javax.swing.JPanel {

    /**
     * Creates new form AdminPageView
     */
    public AdminPageView(JPanel bottomPanel) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdminPageView = new javax.swing.JPanel();
        lblAdminLogin = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        lblAdminPassword = new javax.swing.JLabel();
        txtAdminName = new javax.swing.JTextField();
        btnAdminSubmit = new javax.swing.JButton();
        txtAdminPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(102, 102, 255));

        panelAdminPageView.setBackground(new java.awt.Color(45, 118, 232));

        lblAdminLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblAdminLogin.setText("Admin Login");

        lblAdminName.setText("Admin Name:");

        lblAdminPassword.setText("Password:");

        btnAdminSubmit.setText("Login");
        btnAdminSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminSubmitActionPerformed(evt);
            }
        });

        txtAdminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminPageViewLayout = new javax.swing.GroupLayout(panelAdminPageView);
        panelAdminPageView.setLayout(panelAdminPageViewLayout);
        panelAdminPageViewLayout.setHorizontalGroup(
            panelAdminPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminPageViewLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(panelAdminPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdminSubmit)
                    .addComponent(lblAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdminPageViewLayout.createSequentialGroup()
                        .addGroup(panelAdminPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAdminPassword)
                            .addComponent(lblAdminName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAdminPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdminName, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(txtAdminPassword))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        panelAdminPageViewLayout.setVerticalGroup(
            panelAdminPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminPageViewLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(panelAdminPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminName)
                    .addComponent(txtAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelAdminPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminPassword)
                    .addComponent(txtAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnAdminSubmit)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdminPageView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdminPageView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminSubmitActionPerformed
        // TODO add your handling code here:
//         try {
//        TaskManagementModel taskManagementModel = new TaskManagementModel();
//        
//            String adminName = txtAdminName.getText().trim();
//            String adminPassword = new String(txtAdminPassword.getPassword()).trim();
//            
//        System.out.println("Admin Name: " + adminName);
//        System.out.println("Admin Password: " + adminPassword);
//        
//            if (adminName.isEmpty() || adminPassword.isEmpty()){
//                 JOptionPane.showMessageDialog(this, "Please Fill in Login Details to Access Dashboard!", "Error", JOptionPane.ERROR_MESSAGE);
//            }else{
//            System.out.println("Admin login successful with name: " + adminName);
//            JOptionPane.showMessageDialog(this, "Welcome Admin", "Successful Login", INFORMATION_MESSAGE);
//            }
//             }catch(Exception e){
//                 System.out.println("Invalid Request");
                 // JOptionPane.showMessageDialog(this, "Please Fill in Login Details to Access Admin Dashboard!", "Error", JOptionPane.ERROR_MESSAGE);
                                // }
                 String adminName = txtAdminName.getText().trim();
                 String adminPassword = new String(txtAdminPassword.getPassword()).trim();

                if (adminName.isEmpty() || adminPassword.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please Fill in Login Details to Access Admin Dashboard!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {

                    System.out.println("Admin login successful with name: " + adminName);
                    JOptionPane.showMessageDialog(this, "Welcome " + adminName, "Successful Login", JOptionPane.INFORMATION_MESSAGE);
                    
                                    }
//                AdminDashboardTest adminDashboardTest = new AdminDashboardTest();
//                bottomPanel.add(adminDashboardTest);
//                
//                CardLayout cl = (CardLayout) bottomPanel.getLayout();
//                cl.show(bottomPanel, "AdminDashboardTest");
//                cl.next(bottomPanel);
    }//GEN-LAST:event_btnAdminSubmitActionPerformed

    private void txtAdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminSubmit;
    private javax.swing.JLabel lblAdminLogin;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblAdminPassword;
    private javax.swing.JPanel panelAdminPageView;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JPasswordField txtAdminPassword;
    // End of variables declaration//GEN-END:variables
}
