/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.TaskManagementModel;

/**
 *
 * @author eboka
 */
public class MainFrameUserView extends javax.swing.JPanel {

    /**
     * Creates new form UserPageView
     */
    public MainFrameUserView() {
        initComponents();
        
        bottomPanel.setLayout(new java.awt.CardLayout());
        
       UserPageView userPageView = new UserPageView(this.bottomPanel);
        bottomPanel.add(userPageView);
      
//        CardLayout cl = (CardLayout) bottomPanel.getLayout();
//        cl.next(bottomPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        btnReturn = new javax.swing.JButton();
        btnUserDashboard = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPanel.setBackground(new java.awt.Color(45, 118, 232));

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnUserDashboard.setText("Dashboard");
        btnUserDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserDashboardMouseClicked(evt);
            }
        });
        btnUserDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(btnUserDashboard)
                .addGap(65, 65, 65))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(btnUserDashboard))
                .addGap(32, 32, 32))
        );

        jSplitPane1.setTopComponent(topPanel);

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(bottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDashboardActionPerformed
        // TODO add your handling code here:
       
//        TaskManagementModel taskManagementModel = new TaskManagementModel();
//            String userName = txtUserName.getText().trim();
//            String userPassword = new String(txtPassword.getPassword()).trim();
//        
//            if (getuserName.isEmpty() || getuserPassword.isEmpty()){
//                 JOptionPane.showMessageDialog(this, "Please Fill in Login Details to Access Dashboard!", "Error", JOptionPane.ERROR_MESSAGE);
//             try {
//                 
                UserDashboardTest userDashboardTest = new UserDashboardTest();
                bottomPanel.add(userDashboardTest);
                
                CardLayout cl = (CardLayout) bottomPanel.getLayout();
                cl.show(bottomPanel, "UserDashboardTest");
                cl.next(bottomPanel);

//             }catch(Exception e){
//                 System.out.println("Invalid Request");
//            JOptionPane.showMessageDialog(this, "Please Fill in Login Details to Access Dashboard!", "Error", JOptionPane.ERROR_MESSAGE);
//       
//             }    
            
        
//    new UserDashboard().show();
        
    }//GEN-LAST:event_btnUserDashboardActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        
             UserPageView userPageView = new UserPageView(bottomPanel);
                bottomPanel.add(userPageView);
                
                CardLayout cl = (CardLayout) bottomPanel.getLayout();
                cl.next(bottomPanel);
       
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnUserDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserDashboardMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnUserDashboardMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnUserDashboard;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

  
}
