/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.TaskManagementModel;

/**
 *
 * @author eboka
 */
public class UserPageView extends javax.swing.JPanel {

    /**
     * Creates new form UserPageView
     */
    public UserPageView(JPanel bottomPanel) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUserPageView = new javax.swing.JPanel();
        lblUserLogin = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnUserSubmit = new javax.swing.JButton();
        txtUserPassword = new javax.swing.JPasswordField();

        panelUserPageView.setBackground(new java.awt.Color(45, 118, 232));

        lblUserLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblUserLogin.setText("User Login");

        lblUserName.setText("User Name:");

        lblUserPassword.setText("Password:");

        btnUserSubmit.setText("Login");
        btnUserSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSubmitActionPerformed(evt);
            }
        });

        txtUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUserPageViewLayout = new javax.swing.GroupLayout(panelUserPageView);
        panelUserPageView.setLayout(panelUserPageViewLayout);
        panelUserPageViewLayout.setHorizontalGroup(
            panelUserPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserPageViewLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(panelUserPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUserSubmit)
                    .addComponent(lblUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUserPageViewLayout.createSequentialGroup()
                        .addGroup(panelUserPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUserPassword)
                            .addComponent(lblUserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelUserPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserPassword))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        panelUserPageViewLayout.setVerticalGroup(
            panelUserPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserPageViewLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(panelUserPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelUserPageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPassword)
                    .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnUserSubmit)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUserPageView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUserPageView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPasswordActionPerformed

    private void btnUserSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSubmitActionPerformed
        // TODO add your handling code here:
        
                         String userName = txtUserName.getText().trim();
                 String userPassword = new String(txtUserPassword.getPassword()).trim();

                if (userName.isEmpty() || userPassword.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please Fill in Login Details to Access User Dashboard!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {

                    System.out.println("Admin login successful with name: " + userName);
                    JOptionPane.showMessageDialog(this, "Welcome " + userName, "Successful Login", JOptionPane.INFORMATION_MESSAGE);
                    
                                    }
    }//GEN-LAST:event_btnUserSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUserSubmit;
    private javax.swing.JLabel lblUserLogin;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserPassword;
    private javax.swing.JPanel panelUserPageView;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
